version: '3.7'

services:
  app:
    container_name: app
    restart: always
    build: .
    command: npm start
    volumes: 
      - .:/app
      - /app/node_modules
    env_file: 
      - .env
    ports:
      - 3000:3000